### ISSUE TITLE
Cannot easily use resources of type "shell" when using the GitHub action

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli-action#21]
Hello 👋 

I got the following GitHub workflow: https://github.com/jenkins-infra/jenkins-infra/blob/235c575b88e0df2d7bfc21080960f23460e42822/.github/workflows/updatecli.yaml 

where I'm using updatecli with the resource of type "shell" to call the AWS EC2 command.

Despite https://github.com/updatecli/updatecli/pull/265 (that will solve my issue on the long term), the usage of a `shell` resources is difficult in a github action, because the Docker image of `updatecli` does not provide any common tools such as `wget` / `curl` , `zip` or `tar`, so I add to stop using the github action and use a custom binary installation instead.

I see different ways of improving the situation, each one with its pros and cons (and there might be others as well):

- Add a set of "common" tools inside the `updatecli` Docker image, or on the Github Action's cusotm Docker Image
  - But what set of packages? What is the "bare minimum"? 
- Allows installing packages in the Docker image in GitHub actions. E.g. run the image as the "root" user to allow the "shell" commands to install packages at their ease.
  - Security is not an issue, in the context of github action (because the container runs on a VM where the user already has sudoers)
- Add an "alternative" mode for the github action: instead of executing with the docker image, it  would use the Docker image to install the CLI on the current worker environment, such as https://github.com/marketplace/actions/install-aws-cli-action (depracted as AWS CLI is now installed out of the box on GitHub actions workers).
  -  Doing so would delegate to the end user the act of "personalization" of its environment

**Comment by olblak** [comment]
Considering that there is a specific Dockerfile for the Github action, I would just add common tools such as those mentionned

**Comment by dduportal** [comment]
Additional material: https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user

The default user should be root.
